src/spec/email_config.json
tests/MailerTest.php

Studio: d-77b8ba7cb4e347868f651d65815f2586
Sample: d-9a4699657cb44a03b4949128490cd669
DJ Pro: d-68ce15278586469bab7808953edbe65b
DJ Lite: d-64a960729c4444048f59aa06f23bcc5f
PnT Pro: d-28c44c55ca094f1d9c499175080b5c76
PnT LE: d-6de80a3929334d24ba237b4e936051a5

[WEB-3162] add the following email template

---

src/spec/email_config.json

remove the blank line on the spec file

[WEB-3162] Send link to users trying to download Serato software on mobile

---

src/spec/email_config.json
tests/MailerTest.php

added new template for Backstage opt-outs

[WEB-3094] Added template for Backstage opt-out & update test code

---

src/spec/email_config.json
tests/MailerTest.php

- add iZotope levvel warning template
- update unit test

Add new template - iZotope level warning

---

src/spec/email_config.json
tests/MailerTest.php

[WEB-3901] Implement Sample LE onboarding email in SendGrid

---

src/spec/email_config.json
tests/MailerTest.php

Add new templates
- welcome-to-serato
- password-reset
- password-updated
- change-email-address

[WEB-3523] Add new templates

---

src/spec/email_config.json
tests/MailerTest.php

add the following email templates
Welcome to Serato:  d-5303dfad23c84cd59aa9c785693688ab
Reset password: d-dc88bb49166f4e35a192e374c6a628b8
updated password: d-ee3ad7351b994e16a09a75747b20ac22
change email: d-964ccc1ab3c04b858c8d4726cb13510d

[WEB-3523] merge to master

---

src/spec/email_config.json

update template parameter
"home_url",
"backstage_url",
"support_url",
"facebook_url",
"twitter_url",
"youtube_url",
"instagram_url",
"opted_in"

[WEB-3523] Update template param for welcome to serato

---

src/spec/email_config.json
tests/MailerTest.php

update welcome to serato template parameter
"home_url",
"backstage_url",
"support_url",
"facebook_url",
"twitter_url",
"youtube_url",
"instagram_url",
"opted_in"

[WEB-3523] Update template param

---

src/Mailer.php

Added validate rule for template params

[WEB-3523] Add validate rule for bool at validateTemplateParams

---

src/Mailer.php
src/spec/email_config.json
tests/MailerTest.php

- Add new template 
- Add sendEmail
- Update test code

[WEB-4036] Add new template and update sendEmail logic

---

src/spec/email_config.json
tests/MailerTest.php

DJ Essentials permanent, DJ Expansions permanent DJ Toolkit sub, DJ Club Kit sub.

[WEB-4162] Including email templates for new products.

---

src/Mailer.php
src/spec/email_config.json
tests/MailerTest.php
tests/resources/valid_email_config.json

- Confirm account deactivation email
- Toolkit welcome
- User credit card expiring
- Update from name on all emails

New email templates

---

src/spec/email_config.json

Add BCC for account deactivated email

[WEB-4519] SendGrid: BCC sales on 'Your account has been deactivated' emails

---

src/spec/email_config.json
tests/MailerTest.php

Change template id of invoice email

[WEB-4879] Update Express Checkout UI and Invoices info to reflect that NZ purchases are tax inclusive(Don't merge until it's ready to deploy)

---

src/spec/email_config.json
tests/MailerTest.php

- add new template for subscription plan change immediate and next cycle
- update unit test

[WEB-5642] Add new template for subscription plan change

---

src/spec/email_config.json

This adds the two new email templates into the SDK

[WEB-6065] Trigger new Sendgrid emails for 'credit card trials'

---

src/spec/email_config.json

Add 3 new NFR email templates into the SDK

[WEB-5930] Automated NFR Email

---

src/spec/email_config.json

this updates the email template ID to use the new invoice email template

[WEB-5940] Display full price on discounted invoices 

---

src/spec/email_config.json

I've been trying to figure out a way to create a script or easier way for Mat to test all of these, but I can't figure out a simple way to do it. any suggestions?

[WEB-6764] Sendgrid - Translated templates for free trial emails

---

src/spec/email_config.json
tests/MailerTest.php

- Sample subscription cancellation email template ids added
- Release of this change is marked as v3.0.7-alpha.1. Proper version v3.0.7 will be released once testing is done.

[WEB-7852] Cancel sample subscription email

---

src/spec/email_config.json

- Added translated email ids for different languages

[WEB-9027] Implement translated Sample license activation email content

---

src/spec/email_config.json
tests/MailerTest.php

Changes made
* Added new template
* Updated number of templates

[WEB-9829] - Email Confirmation to My Account Email Update
